import { Tour } from 'nextstepjs';

export const steps: Tour[] = [
    {
        tour: "sidebarTour",
        steps: [
            {
                icon: "👋",
                title: "Welcome to HR Candidate Shortlisting",
                content: "Let's take a quick tour of the main features to help you get started!",
                selector: "#nav-shortlist",
                side: "right",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
            },
            {
                icon: "🎯",
                title: "Shortlist Candidates",
                content: "AI-powered candidate matching. Select a job description, generate evaluation rubrics, and rank candidates automatically.",
                selector: "#nav-shortlist",
                side: "right",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
            },
            {
                icon: "📄",
                title: "JD Library",
                content: "Upload and manage your job descriptions. These will be used to generate custom evaluation rubrics.",
                selector: "#nav-jd-library",
                side: "right",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
            },
            {
                icon: "👥",
                title: "Candidate Database",
                content: "Upload candidate resumes and manage your talent pool. Organize candidates into custom groups.",
                selector: "#nav-candidate-database",
                side: "right",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
            },
            {
                icon: "📊",
                title: "Previous Sessions",
                content: "Review past candidate evaluations and rankings. Track your hiring decisions over time.",
                selector: "#nav-sessions",
                side: "right",
                showControls: true,
                showSkip: false,
                pointerPadding: 10,
                pointerRadius: 8,
            },
        ]
    },
    {
        tour: "shortlistTour",
        steps: [
            {
                icon: "👋",
                title: "Welcome to Candidate Matching",
                content: "Let's walk through the 4-step process of AI-powered candidate shortlisting!",
                selector: "#step-1-card",
                side: "bottom",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
                viewportID: "main-content-viewport",
            },
            {
                icon: "📝",
                title: "Step 1: Select Job Description",
                content: "Choose a job description from your JD Library. This defines the role you're hiring for.",
                selector: "#step-1-card",
                side: "bottom",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
                viewportID: "main-content-viewport",
            },
            {
                icon: "✨",
                title: "Step 2: Choose Evaluation Rubric",
                content: "Review the 3 generated rubrics and select the one that best fits your hiring criteria. You can edit weightages and criteria!",
                selector: "#step-2-card",
                side: "bottom",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
                viewportID: "main-content-viewport",
            },
            {
                icon: "👥",
                title: "Step 3: Select Candidates",
                content: "Choose which candidates to evaluate. Select by group or individually from your candidate database.",
                selector: "#step-3-card",
                side: "bottom",
                showControls: true,
                showSkip: true,
                pointerPadding: 10,
                pointerRadius: 8,
                viewportID: "main-content-viewport",
            },
            {
                icon: "📊",
                title: "View Ranked Results",
                content: "See candidates ranked by fit score with detailed breakdowns, justifications, and AI-generated summaries.",
                selector: "#results-card",
                side: "bottom",
                showControls: true,
                showSkip: false,
                pointerPadding: 10,
                pointerRadius: 8,
                viewportID: "main-content-viewport",
            }
        ]
    }
];
